title: Json Struct
description: |
  # jserver
  - jsonと構造体で扱う値を定義する

definitions:
  id:
    title: ID
    description: ID
    type: integer
    example: 2 

  message:
    title: Meassage
    description: メッセージ
    type: string
    example: "Hello, World." 

  created_at:
    title: Created at
    description: レコード作成日時
    type: string
    example: "2016-05-09T19:45:32Z"

  int:
    title: int
    description: int
    type: integer
    example: 0

  valid:
    title: valid
    descrition: null許容のintでフラグとして利用する
    type: boolean
    example: false

  null_admit_int:
    title: NullAdmitInt 
    description: null許容のint
    type: object
    properties:
      valid:
        $ref: '#/definitions/valid'
      int:
        $ref: '#/definitions/int'

  sample:
    title: Sample 
    description: jsonを扱う構造体
    type: object
    example: 1
    properties:
      null_admit_int:
        $ref: '#/definitions/null_admit_int'
      message:
        $ref: '#/definitions/message'
      created_at:
        $ref: '#/definitions/created_at'

properties:
  sample:
    $ref: '#/definitions/sample'
  null_admit_int:
    $ref: '#/definitions/null_admit_int'

